improve git-grab

diff --git a/bin/git-grab b/bin/git-grab
--- a/bin/git-grab
+++ b/bin/git-grab
@@ -1,32 +1,43 @@
 #!/usr/bin/env bash
 
-set -eou pipefail
+set -euo pipefail
+shopt -s inherit_errexit
 
-if [[ $# != 1 ]]; then
-  me=$(basename ${BASH_SOURCE})
-  echo "USAGE: $me REPO"
-  echo
-  echo "Clones the github repo into ~/src/github.com/org/repo"
-  echo "Where REPO is either a full URL (without the .git) or an ORG/REPO tuple."
-  echo "Example: $me superorbital/git-grab"
-  echo "         $me https://github.com/superorbital/git-grab"
-  exit 2
-fi
+main() {
+  [[ $# == 1 ]] || usage "Missing REPO"
 
-url_or_pair=$1
+  url_or_pair=$1
+  org=$( nth_item_from_end "$url_or_pair" 2)
+  repo=$(nth_item_from_end "$url_or_pair" 1)
+
+  if [[ -d "$HOME/src/github.com/$org/$repo" ]]; then
+    echo "$HOME/src/github.com/$org/$repo is already cloned."
+    exit
+  else
+    mkdir -p "$HOME/src/github.com/$org"
+    cd "$HOME/src/github.com/$org"
+    git clone "https://github.com/${org}/${repo}.git"
+  fi
+}
 
 nth_item_from_end() {
   echo "$1" | rev | cut -d / -f "$2" | rev
 }
 
-org=$( nth_item_from_end "$url_or_pair" 2)
-repo=$(nth_item_from_end "$url_or_pair" 1)
+usage() {
+  [[ $# -gt 0 ]] && echo "ERROR: $*"
+  local me=$(basename "$0")
+  cat <<EOF
+  USAGE: $me [REPO_PAIR|REPO_URL]
 
-if [[ -d "$HOME/src/github.com/$org/$repo" ]]; then
-  echo "$HOME/src/github.com/$org/$repo is already cloned."
-  exit
-else
-  mkdir -p "$HOME/src/github.com/$org"
-  cd "$HOME/src/github.com/$org"
-  git clone "https://github.com/${org}/${repo}.git"
-fi
+  Clones the github repo into ~/src/github.com/org/repo
+  Where REPO is either a full URL (without the .git) or an ORG/REPO tuple.
+  Example: $me superorbital/git-grab
+           $me https://github.com/superorbital/git-grab
+
+EOF
+  exit 1
+}
+
+main "$@"
+
